Added ability to Provide Custome Service Annotations for zeebe-gateway
camunda/camunda-cloud-helm pull request #224
Opened 2022-03-03 12:07 UTC by michelefa1988

What?
I have added the ability for zeebe-gateway service to have its own custom annotations.

Why?
Having ONLY common annotations is not enough. For example if we want to expose each service with a custom domain name

2022-03-03 12:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-cloud-helm?pullRequest=224) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-cloud-helm?pullRequest=224) before we can accept your contribution.<br/><hr/>**Michele Fenech Adami** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-cloud-helm?pullRequest=224) it.</sub>

2022-03-03 13:17 UTC, Zelldon requested changes
Hey @michelefa1988 thanks for your contribution! Please sign our CLA otherwise we can't merge your PR.

Furthermore it would be nice if you could please check our [contribution guide](https://github.com/camunda/camunda-cloud-helm/blob/main/CONTRIBUTING.md). Especially the section about [commit guidelines](https://github.com/camunda/camunda-cloud-helm/blob/main/CONTRIBUTING.md#commit-guidelines) and [tests](https://github.com/camunda/camunda-cloud-helm/blob/main/CONTRIBUTING.md#tests). I would like to see a new test for the service, if you have any question please do not hesitant to ask. The commit messages also need to be adjusted.

Since you added a new property please also make sure to add this to the [README](https://github.com/camunda/camunda-cloud-helm/blob/main/charts/ccsm-helm/README.md#zeebe-gateway) :)

Thanks again for your effort :pray:

2022-03-03 14:19 UTC, michelefa1988 commented
@Zelldon I've done what I could but I am not sure how to go about creating the tests? Is there an example of another annotation which I can use as reference. 

Also I see one of the integrations tests is failing? Is that something which my PR broke?

2022-03-03 14:26 UTC, Zelldon commented
Hey @michelefa1988 thanks for that !

Yes there is already one for the global annotations here https://github.com/camunda/camunda-cloud-helm/blob/main/charts/ccsm-helm/test/zeebe-gateway/service_test.go#L52-L68 you can then just adjust the variable setting to
something like `zeebe-gateway.service.annotations` https://github.com/camunda/camunda-cloud-helm/blob/main/charts/ccsm-helm/test/zeebe-gateway/service_test.go#L56

Regarding the integration tests, I think the issue here is that for external contributors the secrets are not available. I might disable them for PR's then, and only run them on main.

2022-03-03 14:43 UTC, Zelldon commented on charts/ccsm-helm/test/zeebe-gateway/service_test.go
> +			"annotations.foo": "bar",
This needs to be changed, otherwise the test will fail :)
```suggestion
			"zeebe-cluster.service.annotations.foo": "bar",
```

2022-03-03 15:15 UTC, Zelldon commented on charts/ccsm-helm/test/zeebe-gateway/service_test.go
> +			"zeebe-cluster.servics.annotations.foo": "bar",
Typo :)
```suggestion
			"zeebe-cluster.service.annotations.foo": "bar",
```

2022-03-03 16:08 UTC, michelefa1988 commented
@Zelldon  I think I managed to run the tests locally but they are still failing locally, I have no clue why). In case you notice anything wrong please let me know

2022-03-04 08:26 UTC, michelefa1988 commented
@Zelldon  Good Morning, I think all should be ok now. Tests should pass  and helm chart will work

2022-03-04 08:46 UTC, Zelldon reviewed
Thanks @michelefa1988 :rocket: One typo I found and then please squash your commits then we are good to go and I can merge this PR :) Thanks :bow:

2022-03-04 08:46 UTC, Zelldon commented on charts/ccsm-helm/README.md
> +| | `service.annotations` | Defines annotations for the zeeba gateway service | `{ }` |
```suggestion
| | `service.annotations` | Defines annotations for the zeebe gateway service | `{ }` | 
```

2022-03-04 09:12 UTC, Zelldon approved these changes
Awesome thanks so much for your contribution :1st_place_medal:

2022-03-04 09:12 UTC, merged

2022-03-04 09:33 UTC, michelefa1988 commented
@Zelldon what version will include this change? Is there an aloha version or something I can use?

2022-03-04 09:44 UTC, Zelldon commented
@michelefa1988 is out now https://github.com/camunda/camunda-cloud-helm/releases/tag/ccsm-helm-0.0.22